### ISSUE TITLE
Runtime Warning & Segmentation Fault

### ISSUE THREAD

**Issue by oldclesleycode** [thanhdtran/RME#4]
Step 2.2 is unable to run for me -- I'm using GCP to run. 
```
/home/lc2958/RME/rec_eval.py:263: RuntimeWarning: invalid value encountered in divide
  recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))
Traceback (most recent call last):
  File "rme_rec.py", line 365, in <module>
    n_components = n_components)
  File "/home/lc2958/RME/model_runner.py", line 90, in run
    (recall_all, ndcg_all, map_all) = self.eval(U, V)
  File "/home/lc2958/RME/model_runner.py", line 49, in eval
    vad_data=self.vad_data, n_jobs=16, clear_invalid=False, cache=True)
  File "/home/lc2958/RME/rec_eval.py", line 66, in parallel_recall_at_k
    for user_idx in user_idx_generator(n_users, batch_users))
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python2.7/dist-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py", line 381, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This 
could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill t
he worker. The exit codes of the workers are {SIGKILL(-9)}
```

**Comment by thanhdtran** [comment]
Hi, which joblib version are you using?
